language: python
services:
  - docker
python:
  - 3.8
before_install:
  - docker-compose -f docker-compose-test.yml up -d
  - python --version
  - pip install -r requirements.txt
  - pip install -r requirements-travis.txt
  - export PYTHONPATH="${PYTHONPATH}:tp2_utils_package"
script: pytest --cov=.
after_success:
  - coveralls