rabbit_params:
  host: rabbit
  consume_from: yelp_business_city_funny_count
  produce_to:
    - yelp_top_10_funny_cities
  messages_to_group: 100

group_aggregates: []

operations:
  - name: Top10FunnyCities
    type: TopN
    args:
      top_key: city
      value_name: count
      n: 10

message_pipeline:
  - Top10FunnyCities