rabbit_params:
  host: rabbit
  consume_from: yelp_business_funny_reviews_city_count_consumer
  produce_to:
    - yelp_top_10_funny_cities
  messages_to_group: 100

group_aggregates:
  - name: SumCount
    type: Sum
    args:
      sum_value: count
      sum_suffix: ''

operations:
  - name: GroupByCity
    type: GroupBy
    args:
      group_by: city
      aggregates:
        - SumCount
  - name: Top10FunnyCities
    type: TopN
    args:
      top_key: city
      value_name: count
      n: 10

message_pipeline:
  - GroupByCity
  - Top10FunnyCities

message_pipeline_kwargs:
  ends_to_receive: 1
  ends_to_send: 1
  data_path: /data_volume/message_pipeline
  signature: top_10_count_by_city
  commits_until_save: 10

message_set_params:
  set_data_path: /data_volume/message_set