rabbit_params:
  host: rabbit
  consume_from: yelp_reviews_user_stats_consumer_shard2
  produce_to:
    - yelp_user_stats_condition1
    - yelp_user_stats_condition2
    - yelp_user_stats_condition3
  messages_to_group: 1000

group_aggregates:
  - name: ReviewCount
    type: Count
    args: {}
  - name: MeanStars
    type: Mean
    args:
      mean_value: stars
  - name: TextUnique
    type: ValueUnique
    args:
      value_name: text

operations:
  - name: GroupByUser
    type: GroupBy
    args:
      group_by: user_id
      aggregates:
        - ReviewCount
        - MeanStars
        - TextUnique

message_pipeline:
  - GroupByUser

message_pipeline_kwargs:
  data_path: /data_volume/message_pipeline
  signature: user_stats_calculator_shard3
  commits_until_save: 60

message_set_params:
  set_data_path: /data_volume/message_set