rabbit_params:
  host: rabbit
  consume_from: yelp_reviews_user_stats_consumer
  produce_to:
    - yelp_reviews_user_stats_consumer
  messages_to_group: 10000

publisher_sharding:
  by_key: user_id
  shards: 3

group_aggregates: []

operations:
  - name: UserStatsProjector
    type: Project
    args:
      attributes:
        - user_id
        - review_id
        - stars
        - text

message_pipeline:
  - UserStatsProjector

message_pipeline_kwargs:
  signature: user_stats_calculator_sharderer

message_set_params:
  set_data_path: /data_volume/message_set